powerdata<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
x<-paste(powerdata$Date,powerdata$Time)
newcol<-strptime(x,"%d/%m/%Y %H:%M:%S")
newdata<-cbind(powerdata,newcol)
powerdata2<-subset(newdata,newcol>="2007-02-01")
powerdata3<-subset(powerdata2,newcol<"2007-02-03")
powerdata3[,7]<-as.numeric(as.character(powerdata3[,7]))
powerdata3[,8]<-as.numeric(as.character(powerdata3[,8]))
powerdata3[,9]<-as.numeric(as.character(powerdata3[,9]))
plot(powerdata3$newcol,powerdata3[,7],ylim=range(c(powerdata3[,7],powerdata3[,8],powerdata3[,9])),type="l",ylab="Energy Sub Metering",xlab="")
lines(powerdata3$newcol,powerdata3[,9],col="blue")
lines(powerdata3$newcol,powerdata3[,8],col="red")
legend("topright",pch="___",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot 3.png",width=480,height=480)
dev.off()