
powerdata<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
x<-paste(powerdata$Date,powerdata$Time)
newcol<-strptime(x,"%d/%m/%Y %H:%M:%S")
newdata<-cbind(powerdata,newcol)
powerdata2<-subset(newdata,newcol>="2007-02-01")
powerdata3<-subset(powerdata2,newcol<"2007-02-03")
powerdata3[,3]<-as.numeric(as.character(powerdata3[,3]))
plot(powerdata3$newcol,powerdata3$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.copy(png,file="plot 2.png",width=480,height=480)
dev.off()