powerdata<-read.table("household_power_consumption.txt",sep=";",header=TRUE)
newcol<-as.Date(powerdata[,1],"%d/%m/%Y")
newdata<-cbind(powerdata,newcol)
powerdata2<-subset(newdata,newcol>="2007-02-01")
powerdata3<-subset(powerdata2,newcol<="2007-02-02")
powerdata3[,3]<-as.numeric(as.character(powerdata3[,3]))
hist(powerdata3$Global_active_power,main="Global Active Power",xlab="Global Active Power (kilowatts)",col="red")
dev.copy(png,file="plot 1.png",width=480,height=480)
dev.off()